#!/bin/sh
#
# Driver for Lifescan OneTouch UltraEasy
# Copyright (C) 2011 Daniel Thompson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

UPDATE=$HOME/.ue-capture-`date +%Y%m%d`.adb
DB=$HOME/.ue-capture.adb
BACKUP=$DB.bak
VERIFY=$DB.chk

CHK='[0123456789][0123456789][0123456789][0123456789]-[0123456789][0123456789]'

# handle the incoming data
grep $CHK < /dev/stdin | sort > $UPDATE

# ensure the database exists and update the backup
touch $DB
mv $DB $BACKUP

# merge in the new data
sort $BACKUP $UPDATE | uniq > $DB

# verify no data has been lost
sort $BACKUP $DB | uniq -d > $VERIFY
if cmp -s $BACKUP $VERIFY
then
	true
else
	echo "ERROR: database verification failed, restoring from backup" >&2
	mv $DB $DB.corrupt
	mv $BACKUP $BD

	echo "Please manually examine the following files:" >&2
	for i in $DB $DB.corrupt $VERIFY $UPDATE
	do
		echo "   $i"
	done
	exit 1
fi

# verify all data has been merged
sort $UPDATE $DB | uniq -d > $VERIFY
if cmp -s $UPDATE $VERIFY
then
	true
else
	echo "ERROR: incomplete merge, please try again" >&2
	exit 1
fi

# clean up
rm $UPDATE
rm $VERIFY
